on:
  push:
    branches:
      - main

jobs:
  install-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Publish pnpm
        run: pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
